Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2019-02, with the labels that each got.

#78 Upgrade go-gitlab vendor to v0.14.0
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_project_variable.go
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/access_requests.go
  vendor/github.com/xanzy/go-gitlab/boards.go
  vendor/github.com/xanzy/go-gitlab/ci_yml_templates.go
  vendor/github.com/xanzy/go-gitlab/custom_attributes.go
  vendor/github.com/xanzy/go-gitlab/deployments.go
  vendor/github.com/xanzy/go-gitlab/discussions.go
  vendor/github.com/xanzy/go-gitlab/environments.go
  vendor/github.com/xanzy/go-gitlab/event_parsing.go
  vendor/github.com/xanzy/go-gitlab/event_types.go
  vendor/github.com/xanzy/go-gitlab/events.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/go.mod
  vendor/github.com/xanzy/go-gitlab/go.sum
  vendor/github.com/xanzy/go-gitlab/group_members.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/jobs.go
  vendor/github.com/xanzy/go-gitlab/labels.go
  vendor/github.com/xanzy/go-gitlab/license.go
  vendor/github.com/xanzy/go-gitlab/license_templates.go
  vendor/github.com/xanzy/go-gitlab/merge_request_approvals.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/notes.go
  vendor/github.com/xanzy/go-gitlab/pages_domains.go
  vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
  vendor/github.com/xanzy/go-gitlab/pipelines.go
  vendor/github.com/xanzy/go-gitlab/project_badges.go
  vendor/github.com/xanzy/go-gitlab/project_members.go
  vendor/github.com/xanzy/go-gitlab/project_variables.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/protected_tags.go
  vendor/github.com/xanzy/go-gitlab/repositories.go
  vendor/github.com/xanzy/go-gitlab/repository_files.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/session.go
  vendor/github.com/xanzy/go-gitlab/todos.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#80 add missing link and alphabetize side-nav
  website/gitlab.erb
Labels: documentation, size/XS

#83 Use new access levels permissions
  gitlab/resource_gitlab_project.go
  gitlab/util.go
Labels: size/S

#86 Update project `shared_with_groups` option: change type to TypeSet
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
Labels: size/XS

#72 Add new options to project resource
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  gitlab/util.go
  website/docs/r/project.html.markdown
Labels: documentation, size/L

#82 Add Support for Pipeline Triggers
  gitlab/provider.go
  gitlab/resource_gitlab_pipeline_trigger.go
  gitlab/resource_gitlab_pipeline_trigger_test.go
  website/docs/r/pipeline_trigger.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#88 Add approvals_before_merge to Project
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#89 update go-gitlab to v0.14.1
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/project_clusters.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/vendor.json
Labels: dependencies, size/XL

#87 Add support for gitlab project cluster
  gitlab/provider.go
  gitlab/resource_gitlab_project_cluster.go
  gitlab/resource_gitlab_project_cluster_test.go
Labels: dependencies, size/XL

#58 Run ACC tests
  .travis.yml
  gitlab/resource_gitlab_group.go
  scripts/start-gitlab.sh
Labels: size/S

#91 Docs for gitlab_project_cluster
  website/docs/r/project_cluster.html.markdown
  website/gitlab.erb
Labels: documentation, size/M

#92 Fix incorrect link names in documentation.
  website/gitlab.erb
Labels: documentation, size/XS

#93 provider: Enable request/response logging
  gitlab/config.go
Labels: enhancement, size/XS
