Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2019-10, with the labels that each got.

#188 Test EE
  .gitignore
  .travis.yml
  JulienPivotto.gitlab-license.enc
  scripts/license.sh
  scripts/start-gitlab.sh
Labels: size/XS

#189 Pr 163
  gitlab/provider.go
  gitlab/resource_gitlab_project_push_rules.go
  gitlab/resource_gitlab_project_push_rules_test.go
  website/docs/r/project_push_rules.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#187 Fixed build command in README
  README.md
Labels: size/XS

#176 Support for Enabling pre-existing deploy key on a project
  gitlab/provider.go
  gitlab/resource_gitlab_deploy_key_enable.go
  gitlab/resource_gitlab_deploy_key_enable_test.go
  website/docs/r/deploy_key_enable.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#179 Add initialize_with_readme to project
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/r/project.html.markdown
Labels: documentation, size/M

#186 Add gitlab_group_label resource
  gitlab/provider.go
  gitlab/resource_gitlab_group_label.go
  gitlab/resource_gitlab_group_label_test.go
  website/docs/r/group_label.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#197 Return an error if project label is not found
  gitlab/resource_gitlab_label.go
Labels: size/XS
