Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2019-05, with the labels that each got.

#113 Update project_variable.html.markdown
  website/docs/r/group_variable.html.markdown
  website/docs/r/project_membership.html.markdown
  website/docs/r/project_variable.html.markdown
Labels: documentation, size/XS

#96 Implement gitlab service slack
  gitlab/provider.go
  gitlab/resource_gitlab_service_slack.go
  gitlab/resource_gitlab_service_slack_test.go
  website/docs/r/service_slack.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#97 Allow Deploy Keys imports
  gitlab/resource_gitlab_deploy_key.go
  gitlab/resource_gitlab_deploy_key_test.go
  website/docs/r/deploy_key.html.markdown
Labels: documentation, size/M

#102 Update user datasource: allow searching by id and add attributes
  gitlab/data_source_gitlab_user.go
  gitlab/data_source_gitlab_user_test.go
  website/docs/d/user.html.markdown
Labels: documentation, size/XL

#108 website: make example server URL non-clickable
  website/docs/index.html.markdown
Labels: documentation, size/XS

#118 Fix acc tests
  .travis.yml
  gitlab/resource_gitlab_project_cluster_test.go
  scripts/generate-access-token.rb
  scripts/start-gitlab.sh
Labels: size/M

#112 Fix project cluster acc test by adding a fake pem certificate
  gitlab/resource_gitlab_project_cluster_test.go
Labels: size/S

#106 Add `tags` attribute for gitlab project
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  gitlab/util.go
  website/docs/r/project.html.markdown
Labels: documentation, size/S

#115 add container_registry_enabled to project
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#125 Add tag protection
  gitlab/provider.go
  gitlab/resource_gitlab_tag_protection.go
  gitlab/resource_gitlab_tag_protection_test.go
  website/docs/r/branch_protection.html.markdown
  website/docs/r/tag_protection.html.markdown
Labels: documentation, size/XL

#132 Cleans up "project" resource schema and testing framework
  gitlab/helper_test.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  scripts/generate-access-token.rb
  scripts/start-gitlab.sh
Labels: size/XL

#131 Add domain to project cluster
  gitlab/resource_gitlab_project_cluster.go
  gitlab/resource_gitlab_project_cluster_test.go
  website/docs/r/project_cluster.html.markdown
Labels: documentation, size/XS

#134 Add shared_runners_enabled argument to gitlab_project resource
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#104 Add shared_runners_enabled flag in project
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/r/project.html.markdown
Labels: documentation, size/S

#130 Stop silently deleting objects from state
  gitlab/resource_gitlab_branch_protection.go
  gitlab/resource_gitlab_deploy_key.go
  gitlab/resource_gitlab_group.go
  gitlab/resource_gitlab_group_membership.go
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_label.go
  gitlab/resource_gitlab_pipeline_trigger.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_cluster.go
  gitlab/resource_gitlab_project_hook.go
  gitlab/resource_gitlab_project_membership.go
  gitlab/resource_gitlab_project_variable.go
  gitlab/resource_gitlab_service_slack.go
  gitlab/resource_gitlab_tag_protection.go
  gitlab/resource_gitlab_user.go
Labels: size/M

#129 Add GitLab Data Group
  gitlab/data_source_gitlab_group.go
  gitlab/data_source_gitlab_group_test.go
  gitlab/provider.go
  gitlab/resource_gitlab_group.go
  website/docs/d/group.html.markdown
  website/docs/r/group.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#139 Fix documentation group to use parent_id
  website/docs/r/group.html.markdown
Labels: documentation, size/XS
