Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2019-11, with the labels that each got.

#203 fix: Set ForceNew for gitlab_pipeline_shedule.project
  gitlab/resource_gitlab_pipeline_schedule.go
Labels: size/XS

#215 Update dependency go-gitlab
  vendor/github.com/xanzy/go-gitlab/group_clusters.go
  vendor/golang.org/x/net/idna/tables12.00.go
Labels: dependencies, size/XXL

#204 Add gitlab_pipeline_schedule_variable resource
  gitlab/provider.go
  gitlab/resource_gitlab_pipeline_schedule_variable.go
  gitlab/resource_gitlab_pipeline_schedule_variable_test.go
  website/docs/r/pipeline_schedule_variable.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#217 Update go gitlab
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/.travis.yml
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/award_emojis.go
  vendor/github.com/xanzy/go-gitlab/branches.go
  vendor/github.com/xanzy/go-gitlab/commits.go
  vendor/github.com/xanzy/go-gitlab/discussions.go
  vendor/github.com/xanzy/go-gitlab/environments.go
  vendor/github.com/xanzy/go-gitlab/event_types.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/go.mod
  vendor/github.com/xanzy/go-gitlab/go.sum
  vendor/github.com/xanzy/go-gitlab/group_variables.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/merge_request_approvals.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/milestones.go
  vendor/github.com/xanzy/go-gitlab/pipeline_schedules.go
  vendor/github.com/xanzy/go-gitlab/pipelines.go
  vendor/github.com/xanzy/go-gitlab/project_members.go
  vendor/github.com/xanzy/go-gitlab/project_variables.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/repository_files.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/search.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/settings.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/internal/timeseries/timeseries.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#220 Update `access_level` available values
  website/docs/r/group_membership.html.markdown
Labels: documentation, size/XS

#218 Add group runners token to the group data source/resource
  gitlab/data_source_gitlab_group.go
  gitlab/resource_gitlab_group.go
  website/docs/d/group.html.markdown
  website/docs/r/group.html.markdown
Labels: documentation, size/XS

#178 Add kubernetes group clusters
  gitlab/provider.go
  gitlab/resource_gitlab_group_cluster.go
  gitlab/resource_gitlab_group_cluster_test.go
  website/docs/r/group_cluster.html.markdown
  website/gitlab.erb
Labels: dependencies, documentation, size/XL

#166 Fix state not being updated for gitlab_branch_protection
  gitlab/resource_gitlab_branch_protection.go
  gitlab/resource_gitlab_branch_protection_test.go
Labels: size/XS

#223 Make read callbacks graceful for project_share_group, branch_protection and label resources
  gitlab/resource_gitlab_branch_protection.go
  gitlab/resource_gitlab_label.go
  gitlab/resource_gitlab_project_share_group.go
Labels: size/XS

#127 add 'reset_password' arg to user resource
  gitlab/resource_gitlab_user.go
  gitlab/resource_gitlab_user_test.go
  website/docs/r/user.html.markdown
Labels: documentation, size/S

#227 Implement lfs_enabled parameter for gitlab_project
  gitlab/data_source_gitlab_project.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/d/project.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#226 Implement request_access_enabled parameter for gitlab_project
  gitlab/data_source_gitlab_project.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/d/project.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#225 Implement pipelines_enabled parameter for gitlab_project
  gitlab/data_source_gitlab_project.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/d/project.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XS
