Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2019-09, with the labels that each got.

#171 docs(gitlab_project_membership): fix documentation
  website/docs/r/project_membership.html.markdown
Labels: documentation, size/XS

#158 Do not enforce the default_branch in an empty repository
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
Labels: size/M

#173 Resolve triggers pagination issue by calling GetPipelineTrigger
  gitlab/resource_gitlab_pipeline_trigger.go
Labels: size/XS

#167 Add project_share_group resource to share projects with groups
  gitlab/provider.go
  gitlab/resource_gitlab_project_share_group.go
  gitlab/resource_gitlab_project_share_group_test.go
  website/docs/r/project_share_group.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#169 Add support for more variable options (variable_type, masked, environment_scope)
  gitlab/resource_gitlab_group_membership.go
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_group_variable_test.go
  gitlab/resource_gitlab_project_variable.go
  gitlab/resource_gitlab_project_variable_test.go
  gitlab/resource_gitlab_service_jira.go
  gitlab/util.go
  gitlab/util_test.go
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/.travis.yml
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/build_variables.go
  vendor/github.com/xanzy/go-gitlab/commits.go
  vendor/github.com/xanzy/go-gitlab/environments.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/group_variables.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/jobs.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/notes.go
  vendor/github.com/xanzy/go-gitlab/project_import_export.go
  vendor/github.com/xanzy/go-gitlab/project_variables.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/protected_branches.go
  vendor/github.com/xanzy/go-gitlab/repositories.go
  vendor/github.com/xanzy/go-gitlab/resource_label_events.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/settings.go
  vendor/github.com/xanzy/go-gitlab/todos.go
  vendor/modules.txt
  website/docs/r/group_variable.html.markdown
  website/docs/r/project_variable.html.markdown
Labels: dependencies, documentation, size/XL

#168 Clarify gitlab membership import documentation
  website/docs/r/group_membership.html.markdown
  website/docs/r/project_membership.html.markdown
Labels: documentation, size/XS
