Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2020-06, with the labels that each got.

#317 Fixing filename to match other documents. Also escaping underscores …
  website/docs/r/group_ldap_link.html.markdown
Labels: documentation, size/XS

#322 Update go-gitlab to v0.32.0
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/branches.go
  vendor/github.com/xanzy/go-gitlab/commits.go
  vendor/github.com/xanzy/go-gitlab/deployments.go
  vendor/github.com/xanzy/go-gitlab/epic_issues.go
  vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/license.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/milestones.go
  vendor/github.com/xanzy/go-gitlab/pipelines.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/protected_branches.go
  vendor/github.com/xanzy/go-gitlab/repository_files.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/types.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#323 Update to go-gitlab v0.32.1
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/repository_files.go
  vendor/modules.txt
Labels: dependencies, size/M

#289 add attribute remove_source_branch_after_merge to projects
  gitlab/data_source_gitlab_project.go
  gitlab/resource_gitlab_project.go
  website/docs/d/project.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#320 Handle async groups API deletion ack response in tests
  gitlab/resource_gitlab_group.go
  gitlab/resource_gitlab_group_test.go
Labels: size/XS

#311 Add resource for GitHub integration
  gitlab/provider.go
  gitlab/provider_test.go
  gitlab/resource_gitlab_project_push_rules_test.go
  gitlab/resource_gitlab_service_github.go
  gitlab/resource_gitlab_service_github_test.go
  go.sum
  website/docs/r/service_github.html.markdown
  website/gitlab.erb
Labels: dependencies, documentation, size/XL

#327 Fix duplicate `isRunningEE` function
  gitlab/provider_test.go
Labels: size/XS

#328 Creating custom skip function for group_ldap_link tests.
  gitlab/resource_gitlab_group_ldap_link_test.go
Labels: size/M

#340 Improvements to resource_gitlab_user import
  gitlab/resource_gitlab_user.go
  gitlab/resource_gitlab_user_test.go
Labels: size/S
