Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2020-04, with the labels that each got.

#285 Adding the acceptance tests for Gitlab EE
  .github/workflows/acceptance-tests.yml
  .gitignore
  Gitlab-license.encrypted
Labels: size/S

#290 Update go-gitlab to v0.29.0
  go.mod
  go.sum
Labels: size/XS

#291 Support for Gitlab EE soft-delete of groups and projects
  .github/workflows/acceptance-tests.yml
  .github/workflows/unit-tests.yml
  .github/workflows/website.yml
  .travis.yml
  CHANGELOG.md
  GNUmakefile
  gitlab/resource_gitlab_group.go
  gitlab/resource_gitlab_group_label_test.go
  gitlab/resource_gitlab_group_test.go
  gitlab/resource_gitlab_group_variable_test.go
  gitlab/resource_gitlab_label_test.go
  gitlab/resource_gitlab_pipeline_schedule_test.go
  gitlab/resource_gitlab_pipeline_trigger_test.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_hook_test.go
  gitlab/resource_gitlab_project_push_rules_test.go
  gitlab/resource_gitlab_project_test.go
  gitlab/resource_gitlab_project_variable_test.go
  gitlab/resource_gitlab_service_jira_test.go
  gitlab/resource_gitlab_service_slack_test.go
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/applications.go
  vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/group_clusters.go
  vendor/github.com/xanzy/go-gitlab/group_hooks.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/project_clusters.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/protected_branches.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/system_hooks.go
  vendor/modules.txt
Labels: dependencies, size/XL

#274 Add jira flags
  gitlab/resource_gitlab_service_jira.go
  gitlab/resource_gitlab_service_jira_test.go
  website/docs/r/service_jira.html.markdown
Labels: dependencies, documentation, size/S

#295 Updates to README
  README.md
Labels: size/XS
