Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2020-05, with the labels that each got.

#271 Add masked attribute to group variables
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_group_variable_test.go
  website/docs/r/group_variable.html.markdown
Labels: dependencies, documentation, size/XS

#313 Disable Enterprise acceptance tests for pull requests
  .github/workflows/acceptance-tests.yml
Labels: size/XS

#305 Increase MaxIdleConnsPerHost in http.Transport
  gitlab/config.go
Labels: size/XS

#315 Provide a way to specify client cert and key
  gitlab/config.go
  gitlab/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#296 Adding new resource to manage group LDAP links
  gitlab/provider.go
  gitlab/resource_gitlab_group_ldap_link.go
  gitlab/resource_gitlab_group_ldap_link_test.go
  gitlab/testdata/resource_gitlab_group_ldap_link.json
  website/docs/r/group_ldap_link.markdown
Labels: documentation, size/XL

#316 Skip tests when running against CE since only EE supports LDAP links.
  gitlab/resource_gitlab_group_ldap_link_test.go
Labels: size/XS

#302 Update resource gitlab_group_label to read labels from all pages
  gitlab/resource_gitlab_group_label.go
  gitlab/resource_gitlab_group_label_test.go
Labels: size/M

#301 Add management_project_id for Group and Project Clusters
  gitlab/resource_gitlab_group_cluster.go
  gitlab/resource_gitlab_group_cluster_test.go
  gitlab/resource_gitlab_project_cluster.go
  gitlab/resource_gitlab_project_cluster_test.go
  website/docs/r/group_cluster.html.markdown
  website/docs/r/project_cluster.html.markdown
Labels: documentation, size/L

#279 datasource: gitlab_projects
  GNUmakefile
  gitlab/data_source_gitlab_projects.go
  gitlab/data_source_gitlab_projects_test.go
  gitlab/provider.go
  go.mod
  go.sum
  vendor/github.com/mitchellh/hashstructure/LICENSE
  vendor/github.com/mitchellh/hashstructure/README.md
  vendor/github.com/mitchellh/hashstructure/go.mod
  vendor/github.com/mitchellh/hashstructure/hashstructure.go
  vendor/github.com/mitchellh/hashstructure/include.go
  vendor/modules.txt
  website/docs/d/projects.html.markdown
  website/gitlab.erb
Labels: dependencies, documentation, size/XXL

#284 Deploy token
  gitlab/provider.go
  gitlab/resource_gitlab_deploy_token.go
  gitlab/resource_gitlab_deploy_token_test.go
  go.sum
  website/docs/r/deploy_token.html.markdown
Labels: dependencies, documentation, size/XL
