Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2020-09, with the labels that each got.

#358 feature: add project mirror resources to provider
  gitlab/provider.go
  gitlab/resource_gitlab_project_mirror.go
  gitlab/resource_gitlab_project_mirror_test.go
  website/docs/r/project_mirror.html.markdown
  website/gitlab.erb
Labels: dependencies, size/XL

#261 Allow to change user email without recreating the resource
  gitlab/resource_gitlab_user.go
  gitlab/resource_gitlab_user_test.go
Labels: size/S

#264 Add new data source gitlab_group_membership
  gitlab/data_source_gitlab_group_membership.go
  gitlab/data_source_gitlab_group_membership_test.go
  gitlab/provider.go
  website/docs/d/group_membership.html.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#355 Added Quotes in the example for group cluster
  website/docs/r/group_cluster.html.markdown
Labels: documentation, size/XS

#381 Add import_url to gitlab_project
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
  website/docs/r/project.html.markdown
Labels: documentation, size/M

#380 gitlab_project_variable: friendlier error when masked variable is invalid
  gitlab/resource_gitlab_project_variable.go
  gitlab/resource_gitlab_project_variable_test.go
Labels: size/M

#359 Add code_owner_approval_required argument to gitlab_branch_protection resource
  gitlab/resource_gitlab_branch_protection.go
  gitlab/resource_gitlab_branch_protection_test.go
  website/docs/r/branch_protection.html.markdown
Labels: documentation, size/L

#375 Add resource for pipelines email integration
  gitlab/provider.go
  gitlab/resource_gitlab_service_github.go
  gitlab/resource_gitlab_service_pipelines_email.go
  gitlab/resource_gitlab_service_pipelines_email_test.go
  gitlab/resource_gitlab_service_slack.go
  website/docs/r/project_share_group.html.markdown
  website/docs/r/service_github.html.markdown
  website/docs/r/service_jira.html.markdown
  website/docs/r/service_pipelines_email.html.markdown
  website/docs/r/service_slack.html.markdown
  website/gitlab.erb
Labels: dependencies, documentation, size/XL

#356 Add Project-level MR approvals
  gitlab/provider.go
  gitlab/resource_gitlab_project_level_mr_approvals.go
  gitlab/resource_gitlab_project_level_mr_approvals_test.go
  website/docs/r/project_level_mr_approvals.markdown
  website/gitlab.erb
Labels: documentation, size/XL

#337 Clean the state for jira if project doesn't exist
  gitlab/resource_gitlab_service_jira.go
Labels: size/XS

#262 Make password and reset_password exclusive
  gitlab/resource_gitlab_user.go
  gitlab/resource_gitlab_user_test.go
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#362 More group options
  gitlab/resource_gitlab_group.go
  gitlab/resource_gitlab_group_test.go
  gitlab/util.go
  website/docs/r/group.html.markdown
Labels: documentation, size/XL

#382 Fix Deprecated SDK Function Usage
  gitlab/resource_gitlab_deploy_token.go
  gitlab/resource_gitlab_project.go
Labels: size/M

#367 Add instance clusters to Terraform provider
  CHANGELOG.md
  gitlab/provider.go
  gitlab/resource_gitlab_instance_cluster.go
  gitlab/resource_gitlab_instance_cluster_test.go
  website/docs/r/instance_cluster.html.markdown
  website/gitlab.erb
Labels: dependencies, documentation, size/XL

#343 Fix Terraform trying to set `default_branch` to `null`
  gitlab/resource_gitlab_project.go
Labels: size/S

#421 [Breaking] Fix gitlab_project and gitlab_project_share relationship
  docs/resources/project.md
  gitlab/data_source_gitlab_projects.go
  gitlab/helper_test.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_share_group.go
  gitlab/resource_gitlab_project_share_group_test.go
  gitlab/resource_gitlab_project_test.go
Labels: breaking-change

#267 Do not fail when the group member does not exist
  gitlab/resource_gitlab_group_membership.go
Labels: size/XS

#425 Fix the mirror-exists check in the mirror test
  gitlab/resource_gitlab_project_mirror_test.go
Labels: size/XS

#422 Move gitlab_project_push_rules to gitlab_project.push_rules
  docs/data-sources/project.md
  docs/resources/project.md
  docs/resources/project_push_rules.md
  gitlab/data_source_gitlab_project.go
  gitlab/data_source_gitlab_project_test.go
  gitlab/provider.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_push_rules.go
  gitlab/resource_gitlab_project_push_rules_test.go
  gitlab/resource_gitlab_project_test.go
Labels: breaking-change
