Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2020-03, with the labels that each got.

#270 Fix broken links to GitLab Docs for labels
  website/docs/r/group_label.html.markdown
  website/docs/r/label.html.markdown
Labels: documentation, size/XS

#273 Update go-gitlab to v0.28.0
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/.travis.yml
  vendor/github.com/xanzy/go-gitlab/LICENSE
  vendor/github.com/xanzy/go-gitlab/commits.go
  vendor/github.com/xanzy/go-gitlab/deployments.go
  vendor/github.com/xanzy/go-gitlab/event_parsing.go
  vendor/github.com/xanzy/go-gitlab/event_systemhook_types.go
  vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/group_boards.go
  vendor/github.com/xanzy/go-gitlab/group_hooks.go
  vendor/github.com/xanzy/go-gitlab/group_members.go
  vendor/github.com/xanzy/go-gitlab/group_variables.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/issues.go
  vendor/github.com/xanzy/go-gitlab/merge_request_approvals.go
  vendor/github.com/xanzy/go-gitlab/merge_requests.go
  vendor/github.com/xanzy/go-gitlab/pages_domains.go
  vendor/github.com/xanzy/go-gitlab/pipelines.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/settings.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#281 Revert "Fix documentation group to use parent_id (#139)"
  website/docs/r/group.html.markdown
Labels: documentation, size/XS

#216 Use Github Actions Workflows
  .gitattributes
  .github/workflows/acceptance-tests.yml
  .github/workflows/unit-tests.yml
  .github/workflows/website.yml
  .travis.yml
  README.md
Labels: size/M

#282 Fix acceptance tests
  .github/workflows/acceptance-tests.yml
Labels: size/XS
