Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2020-08, with the labels that each got.

#363 Fix unhandled Jira Service error
  gitlab/resource_gitlab_service_jira.go
Labels: size/XS

#364 Fix nil pointer dereferences during error handling
  gitlab/resource_gitlab_deploy_key.go
  gitlab/resource_gitlab_pipeline_schedule.go
  gitlab/resource_gitlab_pipeline_schedule_variable.go
Labels: size/XS

#368 correct management_project_id argument in documentation
  website/docs/r/group_cluster.html.markdown
  website/docs/r/project_cluster.html.markdown
Labels: documentation, size/XS

#342 Fix incorrect description of valid access levels
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#339 Import group labels
  gitlab/resource_gitlab_group_label.go
  gitlab/resource_gitlab_group_label_test.go
  website/docs/r/group_label.html.markdown
Labels: documentation, size/M

#360 Add importer to resource_gitlab_project_push_rules
  gitlab/resource_gitlab_project_push_rules.go
  gitlab/resource_gitlab_project_push_rules_test.go
  website/docs/r/project_push_rules.html.markdown
Labels: documentation, size/S

#378 Bump go-gitlab to v.0.34.1
  gitlab/resource_gitlab_label.go
  gitlab/resource_gitlab_label_test.go
  go.mod
  go.sum
  vendor/github.com/xanzy/go-gitlab/README.md
  vendor/github.com/xanzy/go-gitlab/event_webhook_types.go
  vendor/github.com/xanzy/go-gitlab/gitlab.go
  vendor/github.com/xanzy/go-gitlab/group_clusters.go
  vendor/github.com/xanzy/go-gitlab/group_labels.go
  vendor/github.com/xanzy/go-gitlab/group_members.go
  vendor/github.com/xanzy/go-gitlab/group_milestones.go
  vendor/github.com/xanzy/go-gitlab/groups.go
  vendor/github.com/xanzy/go-gitlab/instance_clusters.go
  vendor/github.com/xanzy/go-gitlab/issues_statistics.go
  vendor/github.com/xanzy/go-gitlab/labels.go
  vendor/github.com/xanzy/go-gitlab/license.go
  vendor/github.com/xanzy/go-gitlab/project_mirror.go
  vendor/github.com/xanzy/go-gitlab/project_snippets.go
  vendor/github.com/xanzy/go-gitlab/projects.go
  vendor/github.com/xanzy/go-gitlab/runners.go
  vendor/github.com/xanzy/go-gitlab/services.go
  vendor/github.com/xanzy/go-gitlab/users.go
  vendor/modules.txt
Labels: dependencies, size/XL

#379 Fix isRunningInEE helper
  gitlab/provider_test.go
Labels: size/XS
