Repository gitlabhq/terraform-provider-gitlab, pull requests merged in 2022-01, with the labels that each got.

#766 Fix docs for gitlab_project_level_mr_approvals import
  docs/resources/project_level_mr_approvals.md
Labels: documentation

#318 Handle manually removed resources
  docs/resources/pipeline_schedule_variable.md
  docs/resources/tag_protection.md
  gitlab/resource_gitlab_branch_protection_test.go
  gitlab/resource_gitlab_deploy_key.go
  gitlab/resource_gitlab_deploy_key_enable.go
  gitlab/resource_gitlab_deploy_key_enable_test.go
  gitlab/resource_gitlab_deploy_key_test.go
  gitlab/resource_gitlab_deploy_token.go
  gitlab/resource_gitlab_deploy_token_test.go
  gitlab/resource_gitlab_group_cluster.go
  gitlab/resource_gitlab_group_cluster_test.go
  gitlab/resource_gitlab_group_label_test.go
  gitlab/resource_gitlab_group_ldap_link.go
  gitlab/resource_gitlab_group_ldap_link_test.go
  gitlab/resource_gitlab_group_membership.go
  gitlab/resource_gitlab_group_membership_test.go
  gitlab/resource_gitlab_group_test.go
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_group_variable_test.go
  gitlab/resource_gitlab_instance_cluster.go
  gitlab/resource_gitlab_instance_cluster_test.go
  gitlab/resource_gitlab_label_test.go
  gitlab/resource_gitlab_pipeline_schedule.go
  gitlab/resource_gitlab_pipeline_schedule_test.go
  gitlab/resource_gitlab_pipeline_schedule_variable.go
  gitlab/resource_gitlab_pipeline_schedule_variable_test.go
  gitlab/resource_gitlab_pipeline_trigger.go
  gitlab/resource_gitlab_pipeline_trigger_test.go
  gitlab/resource_gitlab_project_cluster.go
  gitlab/resource_gitlab_project_cluster_test.go
  gitlab/resource_gitlab_project_hook.go
  gitlab/resource_gitlab_project_hook_test.go
  gitlab/resource_gitlab_project_level_mr_approvals.go
  gitlab/resource_gitlab_project_level_mr_approvals_test.go
  gitlab/resource_gitlab_project_membership_test.go
  gitlab/resource_gitlab_project_mirror_test.go
  gitlab/resource_gitlab_project_share_group.go
  gitlab/resource_gitlab_service_github.go
  gitlab/resource_gitlab_service_github_test.go
  gitlab/resource_gitlab_service_jira.go
  gitlab/resource_gitlab_service_jira_test.go
  gitlab/resource_gitlab_service_pipelines_email.go
  gitlab/resource_gitlab_service_pipelines_email_test.go
  gitlab/resource_gitlab_service_slack.go
  gitlab/resource_gitlab_service_slack_test.go
  gitlab/resource_gitlab_tag_protection.go
  gitlab/resource_gitlab_tag_protection_test.go
  gitlab/resource_gitlab_user.go
  gitlab/resource_gitlab_user_test.go
  gitlab/util.go
Labels: waiting-response, size/XXL

#491 gitlab_user: Do not set skip_confirmation on read
  gitlab/resource_gitlab_user.go
  gitlab/resource_gitlab_user_test.go
Labels: enhancement

#791 Use context-aware CRUD functions and use it in gitlab API calls
  gitlab/data_source_gitlab_group.go
  gitlab/data_source_gitlab_group_membership.go
  gitlab/data_source_gitlab_project.go
  gitlab/data_source_gitlab_project_protected_branch.go
  gitlab/data_source_gitlab_project_protected_branches.go
  gitlab/data_source_gitlab_projects.go
  gitlab/data_source_gitlab_user.go
  gitlab/data_source_gitlab_users.go
  gitlab/resource_gitlab_branch_protection.go
  gitlab/resource_gitlab_deploy_key.go
  gitlab/resource_gitlab_deploy_key_enable.go
  gitlab/resource_gitlab_deploy_token.go
  gitlab/resource_gitlab_group.go
  gitlab/resource_gitlab_group_badge.go
  gitlab/resource_gitlab_group_cluster.go
  gitlab/resource_gitlab_group_label.go
  gitlab/resource_gitlab_group_ldap_link.go
  gitlab/resource_gitlab_group_membership.go
  gitlab/resource_gitlab_group_share_group.go
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_instance_cluster.go
  gitlab/resource_gitlab_instance_variable.go
  gitlab/resource_gitlab_label.go
  gitlab/resource_gitlab_pipeline_schedule.go
  gitlab/resource_gitlab_pipeline_schedule_variable.go
  gitlab/resource_gitlab_pipeline_trigger.go
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_approval_rule.go
  gitlab/resource_gitlab_project_badge.go
  gitlab/resource_gitlab_project_cluster.go
  gitlab/resource_gitlab_project_freeze_period.go
  gitlab/resource_gitlab_project_hook.go
  gitlab/resource_gitlab_project_level_mr_approvals.go
  gitlab/resource_gitlab_project_membership.go
  gitlab/resource_gitlab_project_mirror.go
  gitlab/resource_gitlab_project_share_group.go
  gitlab/resource_gitlab_project_variable.go
  gitlab/resource_gitlab_project_variable_test.go
  gitlab/resource_gitlab_service_github.go
  gitlab/resource_gitlab_service_jira.go
  gitlab/resource_gitlab_service_microsoft_teams.go
  gitlab/resource_gitlab_service_pipelines_email.go
  gitlab/resource_gitlab_service_slack.go
  gitlab/resource_gitlab_tag_protection.go
  gitlab/resource_gitlab_user.go
Labels: enhancement, upstream-terraform, technical-debt

#787 Support `early_auth_check` flag in provider config. Closes #777
  docs/index.md
  gitlab/config.go
  gitlab/provider.go
Labels: enhancement, provider

#793 Add scripts to locally lint, like ci does
  GNUmakefile
  scripts/lint.sh
Labels: enhancement, DX

#588 Add the project access token
  docs/resources/project_access_token.md
  gitlab/provider.go
  gitlab/resource_gitlab_project_access_token.go
  gitlab/resource_gitlab_project_access_token_test.go
Labels: enhancement, new-resource

#796 Support `issues_template` and `merge_requests_template` in project resource
  docs/resources/project.md
  gitlab/resource_gitlab_project.go
  gitlab/resource_gitlab_project_test.go
Labels: enhancement, upstream-api-alignment

#807 Dependabot/go modules/GitHub.com/hashicorp/terraform plugin sdk/v2 2.10.1
  .github/workflows/unit-tests.yml
  go.mod
  go.sum
Labels: dependencies, go

#717 Add environment scope to gitlab_group_variable
  docs/resources/group_variable.md
  gitlab/resource_gitlab_group_variable.go
  gitlab/resource_gitlab_group_variable_test.go
Labels: enhancement

#803 Improve documentation around authentication with GitLab. Closes #557
  gitlab/config.go
  gitlab/provider.go
Labels: documentation

#806 Properly allow arguments `id` or `path_with_namespace` for project data source
  gitlab/data_source_gitlab_project.go
  gitlab/data_source_gitlab_project_test.go
Labels: bug

#805 Upgrade to go-gitlab v0.54.3. Closes #781
  gitlab/resource_gitlab_branch_protection.go
  gitlab/resource_gitlab_deploy_token.go
  gitlab/resource_gitlab_project_access_token.go
  gitlab/resource_gitlab_project_approval_rule.go
  go.mod
  go.sum
Labels: dependencies, go

#817 Enable EE acceptance tests in pull requests
  .github/workflows/pr-acceptance.yml
  .github/workflows/pr-lint.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  GNUmakefile
  tools/tools.go
Labels: EE, DX

#822 Tools apicovered and apiunused
  GNUmakefile
  tools/cmd/apicovered/main.go
  tools/cmd/apiunused/main.go
  tools/go.mod
  tools/go.sum
  tools/passes/apicovered/apicovered.go
  tools/passes/apiunused/apiunused.go
  tools/passes/gen_util.go
  tools/passes/gogitlab/gogitlab.go
  tools/passes/usage/usage.go
  tools/tools.go
Labels: DX

#827 Fix issue in coverage tool
  tools/passes/apicovered/apicovered.go
Labels: bug, DX

#826 Workflows: Fix issue where forks would still run EE tests
  .github/workflows/pr-acceptance.yml
Labels: bug, DX
